global:
  scrape_interval:     15s
  evaluation_interval: 15s
  external_labels:
      monitor: 'node'

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
        - targets: ['host.docker.internal:9090']
         
  - job_name: 'kafka-monitoring'
    scrape_interval: 5s
    static_configs:
        - targets: ['host.docker.internal:8765']

  - job_name: 'node_exporter'
    scrape_interval: 5s
    static_configs:
      - targets: ['host.docker.internal:9100']